### ISSUE TITLE
"Walk for a while" lock screen issue

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#118]
Dear all, 

I am on Ubuntu 17.04 MATE.

"Walk for a while" actually blanks my screen and if I press any key, I am presented with my lock screen.

Does anyone have a similar problem with the latest version?

Yours,

Robert

**Comment by slgobinath** [comment]
Hi,
Could you please elaborate it more? Do you get lock screen after skipping the break/ at the end of break?

Based on the current implementation, you must be able to skip/postpone the break within 5 sec (you can change the time limit in settings) without getting the lock screen. If you skip after 5 sec, you will get the lock screen.

**Comment by orschiro** [comment]
Dear @slgobinath,

I disabled the ability to skip the break.

1. I get the screen "Walk for a While"
2. After the 1 minute countdown my screen blanks (turns black)
3. I press any key to activate my screen again
4. I am presented with the lock screen of Ubuntu MATE

This never happened before in previous versions.

**Comment by slgobinath** [comment]
Hi @orschiro,
That is the expected behavior. Based on this feature request: https://github.com/slgobinath/SafeEyes/issues/102, the user must be able to safely leave the computer. That's why the screen is locked after long breaks. If you do not want this feature, disable the option `Lock the screen after every long break` in Settings.

**Comment by orschiro** [comment]
Now I understand. Thank you!

I did not know this is a new feature. :-)
