### ISSUE TITLE
Allow translation of 'About' window

### ISSUE THREAD

**Issue by pscorek** [slgobinath/SafeEyes#123]
The 'About' window is the only part of Safe Eyes' GUI which currently can not be translated. I believe it would be neat to give users ability of communicating in their language with the whole application.
The app's description is obviously OK to translate.
In case of license box's translation, one can use unofficial translations from gnu.org (available for several languages) or make a new one. If there are arguments for not to translate license box, I think it will be OK to leave it in English.

**Comment by slgobinath** [comment]
I didn't think about it so far. I will add this to the next version with a better description :-)

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/f7ba152aef5f725ecfffda1b4ac51fa596466233.

I decided to leave the license in English since there are only limited number of unofficial translations are available for GPL v3 and GNU recommends translation only to provide a better understanding of the license.
