### ISSUE TITLE
Not starting on startup on Ubuntu MATE 17.04

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#127]
Dear all, 

Despite having added `safeeyes` to my startup application preferences, it is not launching automatically.

I can still start it manually, however. 

Does anyone have a similar issue with launching the application on startup?

**Comment by slgobinath** [comment]
I also have the same problem here in Linux Mint. I will check this.

Thanks

**Comment by slgobinath** [comment]
This happens due to the version change in the desktop file (See https://github.com/slgobinath/SafeEyes/commit/ee5470a927e569708fccdc5bf35bf19bfd6d0cd2). Based on my tests, version 1.1 and 1.2 does not execute Safe Eyes at the startup. Version 1.0 or any invalid versions (like as we had 1.2.0) allows Safe Eyes to run at the startup.

@hartwork if you have any suggestions, please share.

Thanks

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/00886cf4a560bad06a3e85b7d83d163e60f8e0c9

The `version` field is optional according to this document: https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html. Otherwise, must use version `1.0`

**Comment by orschiro** [comment]
I am so glad it's fixed!

I frequently totally forgot about it because it did not start by itself.

**Comment by slgobinath** [comment]
Hi @orschiro,
I also had the same problem. You can fix it manually so that you don't need to wait until the next release.

```
gedit ~/.config/autostart/safeeyes.desktop
```
Delete the line `Version=1.1` in the file and save it.

**Comment by hartwork** [comment]
[`1.1` is a valid value](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), however too recent for some environments as it seems. Removing it as optional looks like a good fix to me at the moment.

**Comment by smith558** [comment]
Same issue. Ubuntu 20 LTS
