### ISSUE TITLE
Default images

### ISSUE THREAD

**Issue by matrixik** [slgobinath/SafeEyes#133]
Hi, in version v1.2.0a10 you removed images from break screens, do you plan to add them again or remove permanently?

Personally I liked them.

**Comment by slgobinath** [comment]
Hi,
Those are removed permanently because some users complained me that they miss the minimal look and feel and the images are not quality enough. Anyhow still, you can add them if you like.

Click on **Break Image** in [Customize Safe Eyes](http://slgobinath.github.io/SafeEyes/#customize) to see how to add break images. The images I've used are attached here: [safeeyes_break_images.zip](https://github.com/slgobinath/SafeEyes/files/964328/safeeyes_break_images.zip)

**Comment by matrixik** [comment]
Thank you
