### ISSUE TITLE
Horrible screen flickering in KDE when SafeEyes darkens the screen for a pause

### ISSUE THREAD

**Issue by peadar-skoutelsky** [slgobinath/SafeEyes#151]
Hi, 
When SafeEyes sets a pause and darkens the screen, it doesn't work properly and the screen flickers horribly, switching from white to black to white to black every few milliseconds. Every time. Basically I skip the pause screen as quickly as possible, it is literally painful for the eyes. (I know, i should look away). 
I am running KDE Neon User Edition with KDE Plasma 5.10.0 (but this also happened under Plasma 5.9.5.)

**Comment by slgobinath** [comment]
Thanks for the bug report. I'll test it in KDE and update it soon.

**Comment by slgobinath** [comment]
Hi,
I've tried KDE Neon with KDE Plasma 5.10.0 in VirtualBox and couldn't reproduce this issue. Could you please start the safeeyes from the terminal and see if there are any errors during the break screen. However, I don't think this is a bug in the code but may be a problem with the graphics driver.

**Comment by Misaghlb** [comment]
the problem is with compositor.. when i set rendering backend to xRender it will be solved but i have tearing problems with xRender in other windows .
another way is:
create kwin rule for safeeyes and in settings > window managment > appearance and fixes, change window type to : force - Utility window
this will disable safeeyes dark window transparency.

my rule:
[safeeyes-kwin-rule.kwinrule.zip](https://github.com/slgobinath/SafeEyes/files/1075407/safeeyes-kwin-rule.kwinrule.zip)

DE: KDE 5.34.0 / Plasma 5.10.1
OS: Manjaro 17.0.2-rc1 Gellivara

**Comment by peadar-skoutelsky** [comment]
Thank you very much Misaghlb, your workaround solved the issue. 
Thank you also Gobinath; I tried running SafeEyes from the terminal (Konsole) but when the flickering started, the terminal didn't display any errors.

**Comment by slgobinath** [comment]
Thanks @Misaghlb and @peadar-skoutelsky.
Do you have any possible workarounds from the Safe Eyes side to fix this problem? If there are anything,  please do let me know.

**Comment by Misaghlb** [comment]
@slgobinath one way is disable opacity for kde plasma DEs

**Comment by slgobinath** [comment]
Great. I'll give a try.

Thanks

**Comment by Misaghlb** [comment]
@slgobinath i did this before my previous comment, and that worked.  because of that i said you can disable opacity.

**Comment by slgobinath** [comment]
Ohh thank you very much. I'll fix it in the next version :-)

**Comment by slgobinath** [comment]
Hi,
I've set the opacity to 1 for KDE in https://github.com/slgobinath/SafeEyes/commit/1943c385d16e0804ab31ba5c0d59b0f3b900a57e. If possible please test the fix by following these steps:

1. Exit the currently running Safe Eyes instance
2. Clone the master branch:
```
git clone https://github.com/slgobinath/SafeEyes.git
```
3. Go to the `SafeEyes` directory
```
cd Safeeyes/
```
4. Set the PYTHONPATH to current directory
```
PYTHONPATH=.
```
5. Run Safe Eyes
```
python3 -m safeeyes
```
(Arch users use `python` instead of `python3`)

**Comment by Misaghlb** [comment]
#159 
it's Working well now.
thanks

**Comment by slgobinath** [comment]
Is it working with opacity?
Anyhow thanks for your support.
