### ISSUE TITLE
Add the manual rest function

### ISSUE THREAD

**Issue by zypangpang** [slgobinath/SafeEyes#186]
I am not sure whether there is a such function in the current version, but I cannot find it. Sometimes I cannot stop my work right at the given time, so I am wondering whether you can add a button for manual break. In that way, I can take a break whenever I want. Thanks a lot.
By the way, I am Chinese. If you want to add the Chinese translation, I can help. : )

**Comment by slgobinath** [comment]
Hi @zypangpang,
Currently, I am working on Safe Eyes 2.0.0 and consider this feature in 2.0.0. I really welcome any translations. Please start a new translation on https://hosted.weblate.org/projects/safe-eyes/translations/

Thanks

**Comment by zypangpang** [comment]
I am looking forward to your Safe Eyes 2.0.0. I have started the Chinese translation on the website you gave. I will work on it when I am free. I think it won't take too long to finish it.

**Comment by slgobinath** [comment]
Thanks.
Take your time because we can include it only in the next release (I am not sure whether 1.2.3 or 2.0.0)

**Comment by zypangpang** [comment]
Hi. I have finished the Chinese translation. You can just add it in your next release. However, I am confused by the string "Maximum time to skip, bypassing the lock screen (in seconds)". Could you tell me what its meaning is exactly? The string only provides limited information.

**Comment by slgobinath** [comment]
Hi,
There is an option to lock the screen (using the default screensaver) after long breaks because long breaks require you to leave the computer and this feature lets you leave without worrying about unauthorized access. However, you can skip the break within 2 seconds (configurable time) without starting the screensaver. In such a scenario you are expected to leave your computer only after 2 seconds.
`Maximum time to skip, bypassing the lock screen (in seconds)` refers that 2 seconds.
Does it make sense?

One more thing, please translate `English` in context: `meta_info.language_name` as `XXX` (Chinese in Chinese).  and `English` in context: `meta_info.language_name_en` as `Chinese` (Chinese in English).
I didn't mention this difference clearly on the official site. I will update the How to translate guide soon.
![selection_001](https://user-images.githubusercontent.com/4003168/30164482-b095b370-93aa-11e7-96df-c0163fb2dba4.png)

For example, please see this French translation source: [fr.json](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/lang/fr.json)

**Comment by zypangpang** [comment]
Got it. I will update my translation soon.

**Comment by zypangpang** [comment]
I have updated my translation. I think you can use it in your next release directly. If you find any problem or mistake in my translation, just tell me.

**Comment by slgobinath** [comment]
Hi,
Weblate will automatically push your changes to GitHub and I will include it in the next release.

Thanks for your contribution :-)

**Comment by slgobinath** [comment]
Added to Safe Eyes 2.0.0 with https://github.com/slgobinath/SafeEyes/commit/d135957f5970d1d823cf2906ca539390408e64a0.
I leave this issue open until I release Safe Eyes 2.0.0.

**Comment by slgobinath** [comment]
Released in Safe Eyes 2.0.0

**Comment by zypangpang** [comment]
I updated to your 2nd version. Everything is awesome. It seems that you changed a lot of texts in the program. Is it the reason why it is still English in my laptop? I tried to change the language, but there seems to be no language button... Anyway, English is not a problem for me. Thanks for the great update.

**Comment by slgobinath** [comment]
Hi,
In Safe Eyes 2.0.0, I also changed the translation to `po` file. Due to that change, I lost most of the existing translations. I manually copy and paste the translations from existing [json](https://github.com/slgobinath/SafeEyes/tree/safeeyes-1.2.2/safeeyes/config/lang) files but not all languages are updated yet.
Of course, there are lot more new strings so if you have time, please have a look at Weblate. I am waiting for all languages to be translated before 2.0.1.

**Comment by zypangpang** [comment]
No problem. I will update the Chinese translation on Weblate soon. :-)

**Comment by slgobinath** [comment]
Thank you very much :-)

**Comment by zypangpang** [comment]
Hi. @slgobinath 
I have finished the Chinese translation. It is available to add to the program now.

**Comment by slgobinath** [comment]
Thank you very much @zypangpang.
It has been pushed to the Github automatically by Weblate. You can see the translation available in the next release.

Thanks again
