### ISSUE TITLE
preferences dialog resets counters

### ISSUE THREAD

**Issue by anarcat** [slgobinath/SafeEyes#200]
i haven't confirmed this with actual tests, but according to the debug log, it sure seems like the preferences panel resets the delay counters. for example, today:

```
2017-10-14 10:00:43,267 [INFO]:[Thread-3] Waiting for 15 minutes until next break
[...]
2017-10-14 10:05:43,339 [INFO]:[MainThread] Saving settings to safeeyes.json
[...]
2017-10-14 10:05:44,352 [INFO]:[Thread-10] Waiting for 15 minutes until next break
```

sure sounds like cheating. ;)

**Comment by anarcat** [comment]
do let me know if you feel that i report too many bugs... ;)

**Comment by slgobinath** [comment]
No problem.
Of course, it is a cheating because if the user changes the interval between two breaks or any other break related configurations we need to reschedule the timer.
I was lazy to check the values that are changing and reschedule depending on what has been changed ^_^.
Anyhow, I consider this as an issue and will fix in upcoming releases.

**Comment by anarcat** [comment]
awesome. current behavior makes sense from a developer's perspective of course, and it's a really tiny corner case.... so no rush, and thanks for considering all my requests so nicely! :)
