### ISSUE TITLE
Add actions in notifications

### ISSUE THREAD

**Issue by Glandos** [slgobinath/SafeEyes#210]
I am a long time user of [workrave](http://www.workrave.org/). It has its advantages and drawbacks compared to SafeEyes, but I am convinced by the notifications of SafeEyes. However, it could be a good experience to have some action buttons in the notification:
  - start the pause immediatly
  - postpone
  - skip

This can be nice to avoid the black screen while doing something important.

**Comment by slgobinath** [comment]
Hi,
I am little against to this idea because adding more features to the notification makes it clunky. Further not all desktop environments support such notifications with multiple buttons.

One of the design goals of Safe Eyes is minimal design. That's why Postpone button on the break-screen is made optional.

I know it is a disappointing but I hope you will understand.

Regards
