### ISSUE TITLE
How to install it under Mac?

### ISSUE THREAD

**Issue by ikozo4** [slgobinath/SafeEyes#291]
Hello, developer, I tried to use PIP installation, but the error was reported. How can I install it?
```bash
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-by9h3o5e/PyGObject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-2n1ys0ph/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-by9h3o5e/PyGObject/
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


☁  /Applications  sudo pip install --upgrade pip
The directory '/Users/kozo4/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/kozo4/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-18.1-py2.7.egg (18.1)

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-zCgZMO/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-k3LPXr/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-zCgZMO/pycairo/
```

Thank you 🤝

**Comment by slgobinath** [comment]
Hi,
I don't think you can run Safe Eyes under Mac because Safe Eyes is highly depending on Linux specific libraries like Gtk and Xlib.
However, I may be wrong about Mac since I am not used to Mac.

**Comment by ikozo4** [comment]
> Hi,
> I don't think you can run Safe Eyes under Mac because Safe Eyes is highly depending on Linux specific libraries like Gtk and Xlib.
> However, I may be wrong about Mac since I am not used to Mac.

Thank you for your answer. Maybe there is no solution under Mac, but I would like to ask you to see if there is any similar software (under Mac)😘.

**Comment by slgobinath** [comment]
According to [Alternativeto](https://alternativeto.net/software/safe-eyes-linux/) website, there is a software called Iris.

**Comment by kostiamol** [comment]
@slgobinath I really like your app, man. But I need to run it on my mac. I tried to install the dependencies but can't fix libffi. Maybe you could wrap the app into a Docker container or somehow improve portability?

**Comment by slgobinath** [comment]
Hi,
Safe Eyes dependencies are highly coupled with Linux. On the other hand, I know nothing about Mac. If anyone forks Safe Eyes and build a Mac version, I appreciate it and happy to share it on Safe Eyes page. I am unable to do it myself due to the lack of time and experience with Mac.

**Comment by kostiamol** [comment]
@slgobinath and what about Docker?

**Comment by slgobinath** [comment]
I Googled on Docker for Desktop applications. In a Docker question thread, I found though it is possible, it requires a lot of XWindow configurations to be done. It may be possible after investing a significant amount of time. However, some features like "Smart Pause" or "Do not Disturb" plugins may not work because they rely on user's activity on the actual system. As a sandbox, docker does not allow an internal application to track external system.

**Comment by kostiamol** [comment]
What a pity(

**Comment by slgobinath** [comment]
I am sorry my friend.
You can try https://iristech.co/ but it is not free.

**Comment by spenat28** [comment]
I found https://www.dejal.com/timeout/ ... it is not as good as this, because it would not suggest what you should do, but similar.

**Comment by sbt-sysadmin** [comment]
merci vielmal, @spenat28

by editing the index.html file located at /Themes/Text.totheme/Documents/index.html, i was able to replicate the SafeEyes reminders (Tightly close your eyes, Roll your eyes a few times to each side, etc.)

i made a copy of the theme so that i could have two Text themes running on Time out- one for the default Time Out "Normal" (Long) break and one for the "Micro" (Short) break.

i actually like Time Out better now because i have more control over the Background color, Opacity and Transition times.

in case anyone is interested, here is my index.html for the Micro breaks:

<!DOCTYPE html>
<html>
<head>
<title>Eye Exercises</title>

<style type="text/css">
body {
    margin: 0;
    padding: 0;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
}

#text {
    color: white;
    font-family: "Helvetica Neue", Helvetica, sans-serif;
    font-size: 55px; /* 500% larger (20px × 5) */
    font-weight: bold;
    text-align: center;
    padding: 20px;
    max-width: 90%; 
    word-wrap: break-word;
    line-height: 1.2; 
}

</style>

<script type="text/javascript">

var breakIdentifier = 'TimeOutText';
var exercises = [
    "Tightly close your eyes",
    "Roll your eyes a few times to each side",
    "Rotate your eyes in clockwise direction",
    "Rotate your eyes in counterclockwise direction",
    "Blink your eyes",
    "Focus on a point in the far distance",
    "Have some water"
];
var currentExerciseIndex = 0;

function getText() {
    window.webkit.messageHandlers.getTimeOutInfo.postMessage('summary');
}

function timeOutInfo(json) {
    var obj = JSON.parse(json);
    
    breakIdentifier = 'TimeOutText-' + obj.breakIdentifier;
    
    if (localStorage[breakIdentifier + '-index']) {
        currentExerciseIndex = parseInt(localStorage[breakIdentifier + '-index']);
    } else {
        currentExerciseIndex = 0;
    }
    
    document.getElementById('text').textContent = exercises[currentExerciseIndex];
    currentExerciseIndex = (currentExerciseIndex + 1) % exercises.length;
    localStorage[breakIdentifier + '-index'] = currentExerciseIndex;
}

function clearText() {
    localStorage.clear(); 
}

</script>

</head>

<body>

<div id="text"></div>

<script>
// clearText();
getText();
</script>

</body>
</html>
