### ISSUE TITLE
Display next long break

### ISSUE THREAD

**Issue by AssafKatz3** [slgobinath/SafeEyes#374]
Hi,
Currently only time of next short break is displayed, optional display of next long break will be great.
Thanks

**Comment by AdamPS** [comment]
Also would be great to have a menu item "Take a long break now".  This seems closely related to the original issue so I thought it was worth combining.  However I can make a new issue if you prefer.

**Comment by AdamPS** [comment]
Ah sorry there is already an issue for my comment: #347

**Comment by AdamPS** [comment]
I would donate €30 for this one.

**Comment by slgobinath** [comment]
Hi, Lets continue our discussion here. What if we show an info like this:
```
Next short break at ... and long break at ...
```

or

```
Next short break at ...
Next long break at ...
```

(whatever looks good)

Would that solve your requirement? Showing both times require some changes in the core API because right now plugins get the information only about the next break. We need to send the information about the next short break and next long break.

**Comment by AssafKatz3** [comment]
Hi,
@slgobinath Yes, it will solve my problem. The request of @AdamPS will be great also. I finally switch from SafeEyes due to this issue.
Thanks

**Comment by AdamPS** [comment]
Thanks @slgobinath.   Yes showing both breaks in the menu sounds good to me thanks.  I would also like to be able to choose to show the long break time in the tray icon instead of the next break time please.  It was working like that in my pull request - I added a core API function `get_break_time(self, break_type = None)`.
