### ISSUE TITLE
Safe Eyes for Android?

### ISSUE THREAD

**Issue by Porrumentzio** [slgobinath/SafeEyes#435]
It would be great if this app could be ported to Android. I leave the suggestion, as I don't have the knowledge to do it by myself

**Comment by slgobinath** [comment]
I have this plan for a long time but I don't have enough time to invest at the moment. Eventually I will come up with a solution.

**Comment by kdnfgc** [comment]
I actually wanted to make this app once I got out of high school.

**Comment by archisman-panigrahi** [comment]
There are many such apps like https://play.google.com/store/apps/details?id=com.saveyoureyesfromdying.blink&hl=en_US, https://play.google.com/store/apps/details?id=com.chill.eye.overseas and many more. 

The current implementation of Safe Eyes cannot be readily ported to Android. I am in favor of closing this issue since many alternatives are already present for Android, so that we can invest our time to make Safe Eyes the best eye protection app for GNU/Linux.
