### ISSUE TITLE
Add support for 20-20-20 rule

### ISSUE THREAD

**Issue by radek-sprta** [slgobinath/SafeEyes#46]
[The 20-20-20 Rule](https://opto.ca/health-library/the-20-20-20-rule)

Would be nice to support it along the eye yoga exercises. Possible implementations I thought off:
* A setting to choose between eye yoga and 20-20-20
* Medium breaks: follow every other short break eye exercise by the 20-20-20 rule
* Run 20-20-20 on a separate timer in addiction to yoga exercises

**Comment by slgobinath** [comment]
Hi,
Thank you for your contribution and suggestion. The 20-20-20 rule can be achieved by adjusting the 15 minutes and 15 seconds break cycle to 20 and 20. Users have the freedom to define their own exercises (See [en.json](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/safeeyes/config/lang/en.json). It can be found in `/opt/safeeyes/config/lang` directory) to 20-20-20 rules or eye yoga. I feel implementing an additional timer for 20-20-20 will increase the complexity of the logic. Since it is achievable using the current implementation, I ignore this issue as won't fix.
