### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by Am0rphous** [slgobinath/SafeEyes#462]
Hi!
I really enjoy your software on Linux based OSes, but i also work with macOS. I tried to install safeeyes with the `pip3` command, but I ran into multiple issues which I'm not competent enough to solve myself.

I would like to know if there are plans on making support for macOS?

**Comment by slgobinath** [comment]
Hi,
Sorry for the late. Safe Eyes heavily depends on XOrg and other Linux APIs. At the moment I do not support Mac or Windows. In the long run I'm planning to get an M1 and if that happens, I will consider porting it to Mac as well. However, I don't expect it to happen in the near future.

In Safe Eyes 3, I am working to remove OS level dependencies as much as possible so that the migration can be easy in the future. If anybody is interested in supporting Mac, I always welcome a PR.

**Comment by Am0rphous** [comment]
Hi! No worries, thank you for the explenation.

**Comment by izikeros** [comment]
@slgobinath - is there some plan breakdown into the tasks needed to support macOS in v3? This would ease and encourage contributing. I don't know what is done and what needs to be done.

I miss SafeEyes after migration from Linux to macOS and perhaps I could help with some contribution.
Thank you for that great piece of free software!

**Comment by slgobinath** [comment]
Hi @izikeros ,
I actually started working on Safe Eyes 3 POC with support for both Linux and Mac but due to other projects, I left the code untouched for months. Safe Eyes 3 will include few major changes:
1. Switching to QT from Gtk (Gtk on Mac doesn't look native out of the box)
2. Complete redesign of Safe Eyes
3. Different incentive model (to motivate myself and contributors) - Safe Eyes will remain FOSS but certain plugins will be available only for donators/contributors (still open source). I am still thinking about it so not finalized yet.

TBH I'm loosing motivation in spending hours into Safe Eyes due to work, family and other projects. I will share the project plan at my earliest but I am planning to open it for contribution only after finalizing the tech stack and the core design.

**Comment by archisman-panigrahi** [comment]
I am in favor of closing this issue, because,

1. The current implementation of safeeyes is not readily portable to MacOS and will require massive rewrite.

2. Developing and testing for MacOS requires access to expensive and proprietary hardware and Apple does not provide docs for how to test an app for MacOS without using their hardware. As a result, porting safeeyes for MacOS just as a hobby is not an option for most developers in our team.

3. Similar software on MacOS may already be available, but GNU/Linux lacks them. Given there is limited resources available to our team, I feel that we can make the maximum impact by utilizing those resources in a focused way by making Safe Eyes a better app in the platforms it already works.

If someone decides to actively work on a MacOS port, please reopen this bug.
