### ISSUE TITLE
How to increase walking break?

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#52]
Hi @slgobinath,

I really like the "Walk for a while exercise". 

How could we add a feature to customise its duration?

Instead of 1 minutes I want 5. :-)

Robert

**Comment by slgobinath** [comment]
Change the Long break duration (in seconds) to 300. But it will be applied to all long breaks.

**Comment by orschiro** [comment]
Hmm. Could we add a feature to customise the duration of any task?

**Comment by orschiro** [comment]
Or a feature to allow the user to add a custom task with a custom duration?

**Comment by slgobinath** [comment]
+1 for your idea but it needs some fundamental/architecture level changes on Safe Eyes break configurations. I leave it as a feature request and later we will decide on how to support this feature.

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/b50cb4b8f78cd0c21e892bb425805dc60ea3d626. From next version, you can override the default time of short/long breaks in safeeyes.json file.
For example, to override the default 1-minute interval of the "walk for a while" break to 5 minutes, modify the `~/config/safeeyes/safeeyes.json` as shown below:
Before modification:
`
...
"long_breaks": [
        {
            "name": "long_break_walk"
        },
        {
            "name": "long_break_lean_back"
        }
    ]
...
`

Change it to:
`
...
"long_breaks": [
        {
            "name": "long_break_walk",
            "time": 5
        },
        {
            "name": "long_break_lean_back"
        }
    ]
...
`

The `time` attribute of long breaks is measured in minutes and for short breaks it is in seconds. A detailed description will be added to the README soon.
For the moment I have no idea of providing a GUI to customize individual breaks since those are only for advanced users and it is an extra effort to add them in GUI ;-)

**Comment by orschiro** [comment]
@slgobinath,

I think this is an excellent advanced solution!

**Comment by slgobinath** [comment]
@orschiro,

Thank you. There are some more features on the list. Overriding optional audible alert (Then you can define that you need audible alert only for the 'close your eyes' break) and customizable image for breaks (Issue #36).

**Comment by slgobinath** [comment]
Included in Safe Eyes [v1.1.5](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.5)
