### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by mcarans** [slgobinath/SafeEyes#528]
SafeEyes is broken for any relatively recent Linux distro probably because of lack of Python 3.11 support.

The master branch works fine. A new release should be made.

The alternative is to check out the SafeEyes repo and run from the command line which is not convenient.

@AdamPS suggested making an issue for this [here](https://github.com/slgobinath/SafeEyes/issues/522#issuecomment-1618692372)

cc @hartwork @slgobinath

**Comment by AdamPS** [comment]
Thanks @mcarans. The benefit of having a release is very clear. The reason for this issue is to work out how to do it. Here is an initial suggestion.

1. Commit more issues?? I have one 75% complete and another less so. Perhaps there are pull requests ready to go.
2. Work out the procedure for creating a release and document it somewhere. I've put my initial ideas into the remaining steps.
3. Prepare for the release. Probably we need to update translations, and increase the version number.
4. Create the release here on github.
5. Create releases elsewhere?? Perhaps this is automatic? If not, then likely we need to ask @slgobinath for help, however he is busy elsewhere.

I have permission to make commits here, and hopefully to create a release. Anyone else can help with most of the steps (I don't have a lot of time myself right now):

- look through pull requests here for any important ones
- work out the procedure for creating a release e.g. look in version history of a past release and investigate the mechanism for translations
- create a PR for the preparation steps (but wait for remaining issues to be committed first)

**Comment by hartwork** [comment]
Hi @AdamPS 

> Thanks @mcarans. The benefit of having a release is very clear. The reason for this issue is to work out how to do it. Here is an initial suggestion.
> 
> 1. Commit more issues?? I have one 75% complete and another less so. Perhaps there are pull requests ready to go.

that's a great plan in general but can and should be independent of getting a soon 2.1.6 with ready-to-ship fixes out the door. Let's untangle what does not need to depend on each other, please.

> 2. Work out the procedure for creating a release and document it somewhere. I've put my initial ideas into the remaining steps.
> 
> 3. Prepare for the release. Probably we need to update translations, and increase the version number.
> 
> 4. Create the release here on github.
> 
> 5. Create releases elsewhere?? Perhaps this is automatic? If not, then likely we need to ask @slgobinath for help, however he is busy elsewhere.

I believe reading and using https://github.com/slgobinath/SafeEyes/blob/master/.github/workflows/release.yml is the answer to 99% of this. Please let me know if you have questions about the workflow. For use, I believe it takes these steps:

1. make a pull request to `master` bumping the version to 2.1.6 or 2.1.6_rc1 (to give the CI a chance to detect last-mile issues)
2. if CI is green, merge to master
3. checkout branch `release`, fast forward to latest remote `master`, push branch `release`, inspect CI logs


> I have permission to make commits here, and hopefully to create a release. Anyone else can help with most of the steps (I don't have a lot of time myself right now):
> 
> * look through pull requests here for any important ones

Please do not make this a blocker for 2.1.6 though. Let's rather do 2.1.7 with more improvements/fixes after.

> * work out the procedure for creating a release e.g. look in version history of a past release and investigate the mechanism for translations

Yes please. There is no in-Git change log btw, none that I could find.

> * create a PR for the preparation steps (but wait for remaining issues to be committed first)

That sounds nice.

**Comment by mcarans** [comment]
@AdamPS Given that SafeEyes is likely broken for anyone with a recent Linux distro (since I would imagine most use Python 3.11), I would prioritise a release over more improvements.

**Comment by slgobinath** [comment]
Hi guys,
Sorry for not being able to help a lot. Let me quickly add some simple steps to README.md on how to release and also create a release.

**Comment by slgobinath** [comment]
Released 2.1.6.
@AdamPS & @hartwork  thanks for all your hard work and support to keep this project live :pray: 

I've added a quick how-to guide here https://github.com/slgobinath/SafeEyes#how-to-release

**Comment by mcarans** [comment]
@slgobinath Thanks very much. I have been able to get the newly released version from the PPA and confirm it works fine.

@AdamPS @hartwork I suggest making another release soon to check the how-to guide covers what you need and that there are no blockers (like permissions) preventing future releases.

**Comment by AdamPS** [comment]
Great many thanks @slgobinath. So are the translations all automatic??

**Comment by slgobinath** [comment]
Hi @AdamPS yes (I hope so :eyes: )

The Ubuntu release is still manual. I came across some solutions to integrate into GitHub CICD but I haven't tested them yet.

**Comment by hartwork** [comment]
> Released 2.1.6.

@slgobinath thank you! :+1: :tada: 


> I've added a quick how-to guide here https://github.com/slgobinath/SafeEyes#how-to-release

Thanks!

Regarding details:
- The version bump can mostly be automated, e.g. `git grep -Fl 2.1.6 | grep -v debian/changelog | xargs sed 's,2\.1\.6,2.1.7,g' -i` would do for 2.1.7, just tried.
- The release date in `safeeyes/platform/io.github.slgobinath.SafeEyes.metainfo.xml` seems to also need an update and an entry in the releasing todo list
- Pushing straight to `master` will end up with red-CI commits on `master` some of the time. My vote for changing that process to go through pull requests also, to keep `master` green.
- The "Important to merge with merge commit" part is not clear to me. Is it important for technical reasons or to keep Git history in a specific shape?

I can make a pull request with adjustments to the readme with the parts that are considered non-controversial. What do you think?

> The release branch is used to automate some steps but is not an ideal solution.

Could you elaborate on its known shortcomings?

>> are the translations all automatic??
> Yes. but I missed adding one more step.

Could you elaborate how changes go from GitHub to Weblate and from Weblate back to GitHub? Is there some magic delay? What are the triggers?

> Running `python3 validate_po.py` from the parent folder to validate that the translations are all correct. (This should be between Step 1 and 2)

Sounds like something to enforce by CI. Would that work?

CC @AdamPS

**Comment by slgobinath** [comment]
Hi @hartwork ,
> I can make a pull request with adjustments to the readme with the parts that are considered non-controversial. What do you think?

Any contribution is welcomed. I agree with you. Better to protect `master` and modify it only through PRs (we have to whitelist weblate bot though; not sure if GitHub free tier supports it or not).

>Important to merge with merge commit

This is a technical reason. At the end of the build, the release branch will be merged into master branch to keep both of them synchronized. If we squash and merge, the release branch will have different commit ids from the master branch and we cannot merge it to master. Merging with a commit will add an additional commit to the release branch but it can be safely merged back to master. FYI: https://github.com/slgobinath/SafeEyes/blob/master/.github/workflows/release.yml#L60-L68

> The release branch is used to automate some steps but is not an ideal solution.

There are a couple of missing features I wish to have but have not implemented yet:
1. Automatic release to Ubuntu launchpad
2. Validating the translation (as you've mentioned)
3. Bumping the version (as you've mentioned)
4. Including proper changelog in the release

> Could you elaborate how changes go from GitHub to Weblate and from Weblate back to GitHub?

Weblate translation is controlled by the Weblate itself and the [weblate](https://github.com/slgobinath/SafeEyes/commits?author=weblate) bot. I have configured [safeeyes.pot](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/safeeyes.pot) file location in Weblate and defined the expected output formats for the translations. Weblate supports custom formats for the output files. In our case, the output files have to be in `<lang-name>/LC_MESSAGES/safeeyes.po` files. Weblate commits all the translations to the repo's master branch. Any changes made to the safeeyes.pot file in our repo will be pulled by Weblate from time to time. We should avoid modifying the translations (safeyes.po files) in the repo since there could be any merge conflicts if someone modifies the translation for the same language.

Sometimes people miss the placeholders in the translated strings which can lead to runtime errors. Here is one such example https://github.com/slgobinath/SafeEyes/issues/441 To prevent releasing such translations, I created a simple script [validate_po.py](https://github.com/slgobinath/SafeEyes/blob/master/validate_po.py) which simply makes sure all the translations have the same number of placeholders as in the original string.

> Sounds like something to enforce by CI. Would that work?

Yes, that's a good idea. We can run `python3 validate_po.py` on PR (before push) and fail the GH Action if there are any corrupted translations.

**Comment by hartwork** [comment]
@slgobinath thanks for elaborating!
I have created pull request #534 now to make the CI check translation files.
With 2.1.6 released by now, is this issue ready to be closed?
