### ISSUE TITLE
CI failing due to invalid translations

### ISSUE THREAD

**Issue by archisman-panigrahi** [slgobinath/SafeEyes#618]
**Describe the bug**
Since this commit https://github.com/slgobinath/SafeEyes/commit/a1d2c7a4ba6b852a9329b2a2a9cc75f6b330426d, the CI check for translation is failing.

I am unsure how to debug this.

**Comment by deltragon** [comment]
Well, it is a valid warning:

```
Number of variables mismatched in fa
Next breaks at %s/%s -> استراحت‌های بعدی در %s
```

The relevant translation being here:

https://github.com/slgobinath/SafeEyes/blob/003812cb96551b03c2b0322baf34ca826f9d0dc8/safeeyes/config/locale/fa/LC_MESSAGES/safeeyes.po#L543-L544

This will also fail at runtime with `TypeError: not all arguments converted during string formatting`.

This isn't even the only error in the Persian translation, unfortunately - however, the `validate_po` script doesn't catch them as it doesn't handle plural translations, apparently:

https://github.com/slgobinath/SafeEyes/blob/003812cb96551b03c2b0322baf34ca826f9d0dc8/safeeyes/config/locale/fa/LC_MESSAGES/safeeyes.po#L449-L453
(Note the "%Id", this should be "%dI" - this is not just a RTL quirk.)

I can fix the specific instance that is failing CI (assuming that ust switching the %s to %s/%s is actually correct in Persian, I don't speak Persian unfortunately.)
However, the bigger issue are the other errors that the validate_po script didn't catch, and the fact that even when CI fails, Weblate will happily commit either way.

I am taking away three TODOs from this situation:

- [ ] Weblate warnings: Weblate actually has built-in [warnings](https://docs.weblate.org/en/latest/user/checks.html#check-formats) for this situation - these don't fire currently because the .po files are missing the `#, python-format` annotations. We should ensure those are added.
- [ ] Fix validate_po.py to find all cases of incorrect annotations.
- [ ] Ensure that Weblate only commits to master when CI passes. We should probably configure Weblate to open a PR instead of pushing to master - it [seems](https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate) like it's possible to auto-approve these PRs.

**Comment by archisman-panigrahi** [comment]
> I can fix the specific instance that is failing CI (assuming that ust switching the %s to %s/%s is actually correct in Persian, I don't speak Persian unfortunately.)

ChatGPT provided identical translation with two %s/%s.

**Comment by deltragon** [comment]
@archisman-panigrahi I have opened a PR with fixes to the first two points.
I am still investigating the third one.
