### ISSUE TITLE
Sudden crashes with 1.1.7

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#69]
Dear all, 

Can someone else confirm sudden crashes of the latest release 1.1.7?

It seems to happen just before the break starts that it crashes. 

However, not on every break. 

I will try to see a pattern!

**Comment by slgobinath** [comment]
Hi,
I wonder it can happen due to a new logic I've added before the break (Change the window mode to normal if there are any fullscreen apps). Can you find any correlations between the crash and the active application that you are working on.

**Comment by orschiro** [comment]
Thanks for your instructions!

You will hear back from me.

**Comment by slgobinath** [comment]
I believe this issue is same as the issue #72. I have fixed that problem with https://github.com/slgobinath/SafeEyes/commit/f20b9602fce546735b0275d4ddebd59c15a3b554. However, I need some more time to test the fix before releasing the new version. If you like, you can apply the fix by replacing the modified files.

**Comment by orschiro** [comment]
Thank you very much @slgobinath. I will, however, wait until I can test a new released .deb file.

**Comment by slgobinath** [comment]
@orschiro,
I have released the new version [1.1.8](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.8) with the fix. Could you please let me know whether it resolves this problem or not?

Thanks

**Comment by orschiro** [comment]
Yes, just installed!

Thank you. :-)
