### ISSUE TITLE
Display next break time next to tray icon?

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#76]
Dear @slgobinath,

I would like to suggest an option to display the next break time next to the tray icon to instantly know when to anticipate the next break. 

What do you think?

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/23067029/b8b3fff2-f51d-11e6-93aa-1034e498a4d0.png)

**Comment by xnakos** [comment]
Having ditched a relevant application (I do not remember which one) just because I could not disable a countdown timer right next to the tray icon, I would suggest that this feature would be totally optional. I am pretty sure there are UX guidelines about activity in the tray. I very much enjoy not anticipating my breaks, i.e. when they come while I am totally focused on work. The countdown timer made me nervous. Next break break time would be much better, though, especially if it was optional! ;) Thanks for the rapid development of SafeEyes!

**Comment by slgobinath** [comment]
@xnakos,
I agree with you. Personally, I also do not like to have a timer there. But two things I consider as the strength of Safe Eyes 1. should be customizable to satisfy every single user, 2. should not compromise the aesthetic design.

I will add this feature as optional for those who want it.

**Comment by orschiro** [comment]
Dear @xnakos and @slgobinath,

I am totally with you both!

Indeed, I agree that a countdown timer would be highly distracting.

Just displaying the next break time is sufficient, I believe. 

Everyone can do the calculus himself, especially given that the current time display is not far. 

There are, however, situations when this is very useful, e.g. when you are in a meeting and forgot to "pause" Safe Eyes in advance. 

Yours,

Robert

**Comment by Joe5** [comment]
![tray](https://cloud.githubusercontent.com/assets/6758999/25303279/d336cc9c-274f-11e7-86c0-dc2444ac30b3.png)

I really like this implementation, it's showing me that a break is coming so I don't start any big work.

I have recently switched from workrave https://github.com/rcaelers/workrave (suspended progress bar timer on the screenshot) to your application and I really miss this feature. **Most of the time I find myself just skipping SafeEyes break because it comes in the worst possible moment interrupting my work focus.**

It does not need to be updated every second, updating every minute is more than enough.

It would be very nice if it can be color coded. For example >= 75% of time showed with no highlight, 50% green 25% red.

At least a static next break time would be nice, but in my opinion this progress bar would be much better solution.

PS: Sorry for my bad English, it's not my native language. And currently, I am focuses on learning another foreign language.

**Comment by slgobinath** [comment]
@orschiro, @Joe5,
I totally agree with you. I tried to add this feature earlier but later focused on migrating to Python 3 and forgot this. I will add this soon according to your requirements but not in v1.2.0 as it requires testing on various desktop environments. Maybe in 1.2.x, you can expect to see this feature.

Thanks

**Comment by orschiro** [comment]
Thank you so much for diligently going after this request!

**Comment by Joe5** [comment]
Thank you, glad to see that and I'm looking forward to it.

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/c03033f33d5f0ee2e2d77263a6253777cf2a278c.

**Comment by orschiro** [comment]
Thank you so much for this new exciting feature, @slgobinath! :-)

**Comment by slgobinath** [comment]
For the moment it just displays the next break time. The time is not a countdown timer but just a static information until the break as in the info menu.
Changing color does not seem to be possible with default tray indicator and I also don't want to add that because it will look odd in some desktop environments. Later depending on the requirements and time, we can change it as a count down timer.

**Comment by orschiro** [comment]
> Later depending on the requirements and time, we can change it as a count down timer.

Without having tested it yet, I think it's fine like this. It should be an easy math task to subtract the next break time from the current time shown by the clock. :-)
